name: Check Runner Resources

on:
  workflow_dispatch: # Bisa dijalankan manual

jobs:
  check-resources:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Display storage usage
        run: |
          echo "ğŸ’¾ Disk usage:"
          df -h
      - name: Remove unused stuff
        run: |
          echo "ğŸ—‘ï¸ Removing stuff"
          sudo rm -rf "/usr/local/share/boost"
          sudo rm -rf "$AGENT_TOOLSDIRECTORY"
      - name: Display memory usage
        run: |
          echo "ğŸ§  Memory usage:"
          free -h

      - name: Display CPU info (optional)
        run: |
          echo "âš¡ CPU Info:"
          lscpu
